#!/bin/sh
yarn --cwd client run buildforce && mkdir -p codegen/built && cp server/src/game-schema.json codegen/built/ && tsc -p codegen && node codegen/built/CompileSchema.js && cp codegen/built/GameSchema.d.ts server/src && tsc -p server
